Integrating Fluent2 HUD into main.
microsoft/fluentui-apple pull request #1034
Opened 2022-06-24 16:40 UTC by rdeassis

### Platforms Impacted
- [x] iOS
- [ ] macOS

### Description of changes

This change integrates the new Fluent2 Heads Up Display into the main branch.
The new version is implemented in SwiftUI and therefore is compatible for use in SwiftUI only environments.
Modifiers that de SwiftUI HUD depends on are also being added (**AnimationCompletionModifier** and **PresentationModifier**)

For context, the PRs that merged this code into the fluent2-tokens (formerly vnext-tokens) branch are referenced below:

- #951 
- #952 
- #960 

### Verification

(how the change was tested, including both manual and automated tests)

| Light Mode                                       | Dark Mode                                      |
|----------------------------------------------|--------------------------------------------|
| ![HUD_UIKit_light](https://user-images.githubusercontent.com/68076145/175593097-f11179de-77ee-4a3b-a195-605a63836408.png) | ![HUD_UIKit_dark](https://user-images.githubusercontent.com/68076145/175596684-fff510dd-dec0-49dd-bd2e-3710678181f3.png) |
| ![HUD_SwiftUI_light](https://user-images.githubusercontent.com/68076145/175597892-80191381-93fc-4e95-a580-867997ce4500.png) | ![HUD_SwiftUI_dark](https://user-images.githubusercontent.com/68076145/175598234-6636f462-9e63-4fc1-a026-41dd331134e3.png) |

### Pull request checklist

This PR has considered:
- [x] Light and Dark appearances
- [x] iOS supported versions (all major versions greater than or equal current target deployment version)
- [ ] VoiceOver and Keyboard Accessibility
- [ ] Internationalization and Right to Left layouts
- [ ] Different resolutions (1x, 2x, 3x)
- [x] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)
- [ ] iPad [Pointer interaction](https://developer.apple.com/documentation/uikit/pointer_interactions)
- [x] [SwiftUI](https://developer.apple.com/tutorials/swiftui) consumption (validation or new demo scenarios needed)
- [ ] Objective-C exposure (provide it only if needed)

2022-06-24 17:15 UTC, huwilkes commented on ios/FluentUI/HUD/HUDView.swift
> -class HUDView: UIView {
Ah, fair.

2022-06-24 17:15 UTC, huwilkes approved these changes

2022-06-24 21:52 UTC, mischreiber requested changes
Blocking merge until we can figure out versioning.

2022-06-24 22:06 UTC, rdeassis commented
> Blocking merge until we can figure out versioning.

This is not an API breaking change, so it shouldn't be tied to issues in versioning.

2022-06-30 16:52 UTC, rdeassis commented
> > Blocking merge until we can figure out versioning.
> 
> This is not an API breaking change, so it shouldn't be tied to issues in versioning.

We will be release the HUD in the same release as other controls that will break the public API.
This will be released in the next minor version update (0.6.0) currently.

2022-07-08 04:46 UTC, mischreiber approved these changes

2022-08-15 17:00 UTC, merged