Make several internal extensions public and bring back UIFontDescriptor's extensions
microsoft/fluentui-apple pull request #400
Opened 2021-01-15 16:24 UTC by zetasq

…or's extensions

### Platforms Impacted
- [x] iOS
- [x] macOS

### Description of changes

1. Make `UIFont` extension methods public again.
2. Make `UITableViewCell` extension method (`hideSystemSeparator()`) public again.
3. Bring back the `UIFontDescriptor` extension methods.

With these changes it would be much easier for Outlook Mobile iOS to migrate from `OfficeUIFabric`(1.1.2) to `FluentUI`. And these functionality exposed could also be used by other consumers.

### Verification

N/A

### Pull request checklist

This PR has considered:
- [x] Light and Dark appearances
- [x] VoiceOver and Keyboard Accessibility
- [x] Internationalization and Right to Left layouts
- [x] Different resolutions (1x, 2x, 3x)
- [x] Size classes and window sizes (iPhone vs iPad, notched devices, multitasking, different window sizes, etc)

2021-01-15 18:05 UTC, rdeassis requested changes
Hi @zetasq.
I'd like to understand more about the context/reasons to add this code into FluentUI.
We can sync offline about details.

2021-01-15 18:05 UTC, rdeassis commented on ios/FluentUI/Extensions/UITableViewCell+Extension.swift
> +public extension UITableViewCell {
In what objects this extension will be used? Plain UITableViewCell instances?
 The functionality should be offered through the MSFTableViewCell (TableViewCell) internally.

2021-01-15 18:05 UTC, rdeassis commented on ios/FluentUI/Extensions/UIFontDescriptor+Extension.swift
> +public extension UIFontDescriptor {
These seem to be just helper functions that don't necessarily align with any FluentUI standard.
Why should FluentUI be the best place to host this code?

2021-01-19 21:55 UTC, sophialee0416 commented on ios/FluentUI/Extensions/UITableViewCell+Extension.swift
>          separatorInset = UIEdgeInsets(top: 0, left: max(UIScreen.main.bounds.width, UIScreen.main.bounds.height), bottom: 0, right: 0)
UIScreen usage is not encouraged (https://github.com/microsoft/fluentui-apple/issues/77)

2021-01-21 03:02 UTC, zetasq commented
After offline sync it seems better to keep these helper functions from public exposure (client could depend more on controls instead of helper function logic).

2021-01-21 03:02 UTC, closed without merging